### ISSUE TITLE
Improve responsive handling of banner section

### ISSUE THREAD

**Issue by tollmanz** [thethemefoundry/make#160]
There have been many reports of difficulties with the responsive handling of the banner sections. We need to look into making this a better experience.

**Comment by scottrrollo** [comment]
Reply to: https://thethemefoundry.com/questions/topic/landing-page-layout-banner-does-not-render-well-on-mobile-phone-in-portrait/

**Comment by scottrrollo** [comment]
Done! Now when a **Banner** section's **Responsive behavior** is set to **Default**, content will always appear vertically centred.

@coreymckrill Once this is deployed, please [notify Malcolm](https://thethemefoundry.com/questions/topic/landing-page-layout-banner-does-not-render-well-on-mobile-phone-in-portrait/).
