### ISSUE TITLE
Gallery section items' description content gets truncated prematurely

### ISSUE THREAD

**Issue by coreymckrill** [thethemefoundry/make#165]
As [reported by a Make Plus user](https://thethemefoundry.com/questions/topic/overlay-text-being-truncated-in-gallery/):

> i have a gallery on my page ... and if you check out the 2nd image (top row, right side) you will see that the text i am trying to overlay is cut off.

I have recreated the issue on a local install. When the gallery section has two columns, the item description container, which is set to `height: 60%`, doesn't fill the available space:

![gallery_2](https://cloud.githubusercontent.com/assets/916023/3781659/ec317cf0-1998-11e4-86ee-895a0c073783.png)

However, when the gallery section is set to four columns, the description container fits appropriately:

![gallery_4](https://cloud.githubusercontent.com/assets/916023/3781675/04ea04e2-1999-11e4-962e-b84d4c147715.png)

(Obviously the content still gets cut off, but it is at the expected bottom edge of the item.)

@scottrrollo can we change the layout styles for these gallery items so the description container will always will all the available space?

**Comment by scottrrollo** [comment]
Fixed!

**Comment by scottrrollo** [comment]
Once this is deployed, users will need to rebuild their existing **Builder** pages by clicking **Publish**.

**Comment by coreymckrill** [comment]
Thanks @scottrrollo !
