### ISSUE TITLE
Allow Builder pages to use featured image

### ISSUE THREAD

**Issue by tollmanz** [thethemefoundry/make#190]
Our modification of the page edit screen causes the featured image field to be removed when using the builder. There should be an easy way for developers to change this behavior without having to modify JS.

**Comment by coreymckrill** [comment]
Update: we decided on a compromise here: the featured image functionality will be available on Builder pages (so you can set/remove a featured image), but the front end template still won't render one.

The reasoning is that the two layout options for featured images on the other views don't really make sense with the Builder layout, so a user can just add their featured image into one of the Builder sections if they want.

The advantage of still being able to _set_ a featured image, even if it doesn't appear in the template, is that there are other contexts where a Builder page might appear where a featured image would be appropriate. One example is using the Posts List section from Make Plus to output a grid of pages.

Here is the commit for this change:
https://github.com/thethemefoundry/make/commit/8a19005f11a3aa4071925e7105fb0658d06581ee

**Comment by coreymckrill** [comment]
This was deployed in 1.6.2
