### ISSUE TITLE
Child theme: improve parent stylesheet loading

### ISSUE THREAD

**Issue by coreymckrill** [thethemefoundry/make#217]
https://thethemefoundry.com/questions/topic/difficulty-with-css-overrides-due-to-way-make-custom-css-is-implemented/

Related: http://justintadlock.com/archives/2014/11/03/loading-parent-styles-for-child-themes

We just need to make sure that if we change how stylesheets are loaded, and the order that styles load, we don't cause problems for folks who are already using the child theme.

**Comment by lamosty** [comment]
I like @justintadlock solution to the problem and think we should go for it. Or are there any downsides to his approach?

**Comment by coreymckrill** [comment]
@lamosty I believe the only complication is that if we start loading the parent and child theme's stylesheets from the parent **functions.php** file, folks that have existing child themes will end up loading the parent stylesheet _twice_.

One workaround might be to add a version constant to the child theme and check for that before using the new method. But I haven't fully thought through that yet.

**Comment by danfascia** [comment]
I posted about this on the support forum with a solution based on the Justin Tadlock approach.

https://thethemefoundry.com/questions/topic/imrpoved-child-theme-css-handling-without-import/

What do you think about changing the master child-theme to adopt this approach... I can see no negatives and it does not impact on people who have already built a child-theme the @import way.

It results in much better WP standard CSS handling for plugins etc...

**Comment by coreymckrill** [comment]
^ This should address the issue. It will go out in the next release.

**Comment by coreymckrill** [comment]
The Justin Tadlock approach is now implemented in version 1.6.0 of Make, as long as you are using version 1.1.0 of the child theme.
