### ISSUE TITLE
Multiplying unused widget positions can't be deleted

### ISSUE THREAD

**Issue by newlocalmedia** [thethemefoundry/make#219]
While duplicating layout sections, creating and deleting widget positions with the page builder, I satrted to get redundant or "ghost" widget positions showing up in the widget manager that I could not delete. (They would not appear in the Customizer however.) First I had 2 and then 3 copies of some widget positions showing up in the widget manager. 

Here is the content of _options table field ttfmp-builder-sidebars at one point. There should only be two widget positions named Home 1 and Home 2 but here there are 3 sets with one apparently attached to a post ID for a regular post rather than a page:

`a:6:{s:19:"227-1405636131846-1";a:2:{s:2:"id";s:19:"227-1405636131846-1";s:5:"label";s:6:"Home 1";}s:19:"227-1405636131846-2";a:2:{s:2:"id";s:19:"227-1405636131846-2";s:5:"label";s:6:"Home 2";}s:19:"227-1415865278047-1";a:2:{s:2:"id";s:19:"227-1415865278047-1";s:5:"label";s:6:"Home 1";}s:19:"227-1415865278047-2";a:2:{s:2:"id";s:19:"227-1415865278047-2";s:5:"label";s:6:"Home 2";}s:19:"201-1415865278047-1";a:2:{s:2:"id";s:19:"201-1415865278047-1";s:5:"label";s:6:"Home 1";}s:19:"201-1415865278047-2";a:2:{s:2:"id";s:19:"201-1415865278047-2";s:5:"label";s:6:"Home 2";}}`

Deleting all my added widget positions and even their pages doesn't help. Is there a way to completely flush all custom widget positions? This happened after the upgrade to Make 1.4.4.

**Comment by coreymckrill** [comment]
Moving this over to our other repo since this is a Make Plus issue.
