### ISSUE TITLE
Date and comments in Google Chrome browser on two lines

### ISSUE THREAD

**Issue by Willem-Siebe** [thethemefoundry/make#228]
Hi,

It seems that white space in the HTML code is causing this effect in Google Chrome:

![image](https://cloud.githubusercontent.com/assets/5107354/5408890/cf9292e8-81e2-11e4-9afd-35dd93942bdb.png)

Removing the white-space in the HTML code solves it.

Kind regards,

Willem

**Comment by coreymckrill** [comment]
@Willem-Siebe the latest version of Make (1.4.8) should address the line break issue with comment counts.
