### ISSUE TITLE
Update Make video thumbnail

### ISSUE THREAD

**Issue by scottrrollo** [thethemefoundry/make#232]
@coreymckrill Can you please update Make's video thumbnail to use the following asset?

![video-thumbnail](https://cloud.githubusercontent.com/assets/1041614/5713498/3120c510-9b11-11e4-8995-4a5db2e1dd03.png)

Here's an example of the current (now old) video thumbnail:

https://thethemefoundry.com/docs/make-docs/getting-started/installing-make/

**Comment by coreymckrill** [comment]
Done.
