### ISSUE TITLE
Sub-menu drop down not working correctly on some iPads

### ISSUE THREAD

**Issue by coreymckrill** [thethemefoundry/make#234]
https://wordpress.org/support/topic/make-theme-menu-not-working-on-ipad?replies=14

Some iPad versions, and perhaps some other touchscreen devices, don't do a great job of handling submenu dropdowns that reveal on "hover".

**Comment by scottrrollo** [comment]
Related: https://wordpress.org/support/topic/header-image-taking-over-on-mobile?replies=5#post-6630696

To recreate the user's problem:

1. Reduce the size of your browser window until you see the mobile menu.
2. Refresh the browser.
3. Toggle the mobile menu.

You'll notice the background image jumps on toggle.

**Comment by melissajohill** [comment]
Another report: https://thethemefoundry.com/questions/topic/dropdown-menu-not-working-on-ipad/

**Comment by scottrrollo** [comment]
See: https://wordpress.org/support/topic/mobile-menu-unresponsive-for-make-theme?replies=3

**Comment by melissajohill** [comment]
Like the related issue Scott posted above: https://wordpress.org/support/topic/background-images-on-mobile-devices?replies=3

**Comment by melissajohill** [comment]
The mobile menu is not working even on my browser in these two (new) reports:

* https://wordpress.org/support/topic/mobile-view-make-theme?replies=9#post-6811365
* https://wordpress.org/support/topic/mobile-menu-unresponsive-for-make-theme?replies=7#post-6813750

**Comment by coreymckrill** [comment]
There appears to be a few different issues being reported in this ticket. One is a problem with the dropdown sub-menus that appear in the desktop view. Another relates to the header image in mobile view. Another involves the Mobile Menu button not revealing the navigation menu when clicked.

I'm going to rename this ticket to be more explicitly about the first issue, and then open new tickets for these other issues.
