### ISSUE TITLE
Cyrillic subset of Google Fonts not working in Firefox or IE

### ISSUE THREAD

**Issue by coreymckrill** [thethemefoundry/make#235]
https://wordpress.org/support/topic/google-fonts-do-not-render-cyrillic-symbols-on-firefox-ie?replies=4#post-6485255

**Comment by coreymckrill** [comment]
https://wordpress.org/support/topic/the-problem-of-correctly-display-fonts-in-ff-and-ie?replies=1

**Comment by nvartolomei** [comment]
Looks like the problem is in how browsers handle urls, also subsets don't work in Safari too. If I remove urlencode and change esc_url into esc_url_raw then problem is solved.

**Comment by coreymckrill** [comment]
Interesting. Thanks for weighing in on this, @nvartolomei. We will take another look at this.

**Comment by nvartolomei** [comment]
@coreymckrill I found something else too, the problem with google fonts is that it does need the ampersand to be actually an ampersand and not escaped as &amp; or other way. `esc_url` escapes it, and urlencode too, can't figure out why this works in Chrome.

**Comment by coreymckrill** [comment]
@nvartolomei ^ I believe this commit fixes the issue. If you would like to try it out, use this version of the **inc/customizer/fonts.php** file:

https://github.com/thethemefoundry/make/blob/86d7a1f2ee1268bf2224bdff484df3dc8ea2f9e3/src/inc/customizer/fonts.php

**Comment by coreymckrill** [comment]
Version 1.5.2 has been submitted to WP.org, and it includes this fix.
