### ISSUE TITLE
Fatal Error: /inc/customizer/controls.php non-existent

### ISSUE THREAD

**Issue by teamAris** [thethemefoundry/make#241]
Just tried to use the customizer on a fresh install of v1.5.0 and get a fatal error here:

https://github.com/thethemefoundry/make/blob/master/src/inc/customizer/bootstrap.php#L379

The file in question 'controls.php' does not exist.

**Comment by scottrrollo** [comment]
@teamAris Sorry to hear about this. @coreymckrill Will be sure to look into this first thing next week.

Which version of WordPress are you using?

**Comment by teamAris** [comment]
It's cleared up in 4.1.1, the error happened in 3.9.1

**Comment by scottrrollo** [comment]
Sounds good, @teamAris. We do intend to officially drop support for WordPress 3.9 soon.

**Comment by coreymckrill** [comment]
FYI the latest patch release fixes this issue. The next minor release will officially drop support for < 4.0.
