### ISSUE TITLE
Allow Custom Name on Sections for # Links

### ISSUE THREAD

**Issue by lauzierj** [thethemefoundry/make#243]
Site builders should be able to provide a unique alpha-numeric string when editing a section's settings. This would be applied to an element immediately inside the <section> as an id attribute to allow for URLs linking directly to those sections. Doing this would make it much easier to build an easily navigable single-page website.

**Comment by scottrrollo** [comment]
Thanks for opening this ticket, @lauzierj! This is something we plan to add in a later version.

Also see #203

**Comment by coreymckrill** [comment]
Custom values for both id and class attributes on the section wrapper have been implemented as an enhancement in version 1.6.0 of Make Plus.
