### ISSUE TITLE
Child theme @import statement

### ISSUE THREAD

**Issue by lamosty** [thethemefoundry/make#247]
Using `@import url( '../make/style.css' );` in child theme's `style.css` is not a good idea since [it is slower](https://kovshenin.com/2014/child-themes-import/) than normal `<link>` HTML tag.

**Comment by coreymckrill** [comment]
Thanks @lamosty . I agree that the `@import` tag is not ideal. We have another ticket open for this #217, but we haven't settled on the best implementation yet. I'm going to close this in favor of the other ticket, to keep things consolidated.
