### ISSUE TITLE
max-width in navigation's secondary menu

### ISSUE THREAD

**Issue by lamosty** [thethemefoundry/make#248]
Is there a reason why `max-width: 250px;` is included in `scaffolding.scss` on line 534? If I have a little longer menu item, subitems are not going till the end of the section as shown on screenshot below:

![image](https://cloud.githubusercontent.com/assets/4988512/6688732/0c8a10ae-ccb6-11e4-9b60-6cecea539013.png)

**Comment by scottrrollo** [comment]
@lamosty Feel free to increase that value in your child theme. Adding a max-width prevents display issues where a sub-menu bleeds over the browser edge.

**Comment by lamosty** [comment]
@scottrrollo I see, thanks for the tip.

I've tried to bleed it over the edge but it couldn't happen in this particular situation. Whether the browser width is > 800px or < 800px, the links in the menu with its sub-menu get wrapped on multiple lines (as it should be).

![image](https://cloud.githubusercontent.com/assets/4988512/6725443/a73ba9ec-ce09-11e4-8a9a-88bd664dbe50.png)

After installing and activating the theme, I was unpleasantly surprised that I have to fix CSS styles before getting the site live because of the issue shown on the 1st picture in my 1st post. Not a big deal, I know, but if that `max-width` servers no purpose, it could be removed. However, I might be missing something and tested it only in Chrome.

**Comment by scottrrollo** [comment]
Thanks for your feedback, @lamosty! It is [common for themes to cap the sub-menu width](https://github.com/Automattic/_s/blob/master/style.css#L560), but  I'll definitely take a second look.
