### ISSUE TITLE
Header image expands behind mobile menu items when Mobile Menu toggle is clicked.

### ISSUE THREAD

**Issue by coreymckrill** [thethemefoundry/make#252]
From [this ticket](https://github.com/thethemefoundry/make/issues/234#issuecomment-76509669):

> To recreate the user's problem:
> 
>    Reduce the size of your browser window until you see the mobile menu.
>    Refresh the browser.
>    Toggle the mobile menu.
> 
> You'll notice the header background image jumps on toggle.

@scottrrollo I'm not sure this is actually a bug. The header image is a background for the whole site header, and the mobile menu is within the site header, so when the mobile menu expands to show the menu items, the background will naturally change/expand to fill the new site header shape.

I can see how this isn't ideal in some situations, but there are workarounds, such as using the Logo slot instead of a header background image. Unless I'm missing something here?

**Comment by scottrrollo** [comment]
> … the background will naturally change/expand to fill the new site header shape.

You're right, @coreymckrill. Let's mark this ticket as an **enhancement**.

**Comment by coreymckrill** [comment]
Perhaps we could add a background color to the mobile menu dropdown, instead of having it be transparent.

**Comment by scottrrollo** [comment]
When the menu is toggled, the background image changes scale. It's this change in scale that I find most distracting.
