### ISSUE TITLE
H1 Title for Text Headers Word Spacing affects Site Title and not Page Title

### ISSUE THREAD

**Issue by tonyzeoli** [thethemefoundry/make#254]
When changing the Word Spacing for H1 Text Headers, the change affects the Site Title and not the Page Title.

Didn't test H2, etc., but I suspect you want to test them to make sure they affect just the H2 Text Header and nothing else.

**Comment by coreymckrill** [comment]
Good catch, @tonyzeoli ! Thanks for the report. We will work on a fix and check the other headers as well.

**Comment by coreymckrill** [comment]
^ That should fix the immediate problem. There may be other typography conflicts that haven't surfaced yet.
