### ISSUE TITLE
How do you change Text Header color?

### ISSUE THREAD

**Issue by tonyzeoli** [thethemefoundry/make#255]
I can't find where to change the text header color. Is there no setting for this?

**Comment by coreymckrill** [comment]
Hi @tonyzeoli 

Text headers don't have their own color picker. The _Text Color_ option under the _Global_ section of Color sets the text header color.

Please ask support questions in the [Make support forum](https://wordpress.org/support/theme/make). The issues section of this GitHub repo is [only for bug reports and feature requests](https://github.com/thethemefoundry/make#contributing).

**Comment by tonyzeoli** [comment]
Okay, thanks...will do. Sorry!
