### ISSUE TITLE
Style Kit reset button should set drop-down back to default

### ISSUE THREAD

**Issue by joelworsham** [thethemefoundry/make#256]
When clicking "Reset" on the style kit (when in the customizer), if there was a style kit set from the dropdown, the dropdown should be changed back to "Default".

This is a small issue, and just semantic, but something I noticed confuse someone for a wee moment.

**Comment by coreymckrill** [comment]
Good point, @joelworsham, although _Reset_ actually switches everything back to whatever was last saved, so not necessarily the "Default" settings. Perhaps we could add a blank option to the dropdown and change it to that when the button is clicked.

**Comment by coreymckrill** [comment]
Style Kits have been removed from Make Plus in 1.7.0, so I'm going to close this.
