### ISSUE TITLE
CSS rules prevent embedding Google Maps with specific dimensions

### ISSUE THREAD

**Issue by coreymckrill** [thethemefoundry/make#262]
We have some [rules in the stylesheet](https://github.com/thethemefoundry/make/blob/1.5.2/assets/sass/patterns.scss#L71-L80) that force embedded Google Maps to fill the width of the container. I'm assuming these were put there in order to make the embeds responsive? The side effect is that they cause problems when people are trying to embed a map with specific dimensions, like in this [help thread](https://wordpress.org/support/topic/google-maps-widget-plugin-conflict?replies=2).

**Comment by coreymckrill** [comment]
^ This is a temporary fix. We should figure out a better way to handle these embeds to allow for specific dimensions.

**Comment by melissajohill** [comment]
Here's another user having problems with this to update when we have a better solution: https://thethemefoundry.com/questions/topic/footer-depth/#post-51263
