### ISSUE TITLE
how to add a custom css textbox to customizer?

### ISSUE THREAD

**Issue by adampotocki** [thethemefoundry/make#263]
Is there a way i can use the TTFMAKE_CSS class to add a custom css textbox into the make theme customizer? Inside say the General section?

**Comment by coreymckrill** [comment]
Hi @adampotocki !

Good question. In this case, the **TTFMAKE_CSS** class probably isn't the right tool for the job. It is intended to be used to procedurally generate CSS rules based on other settings in the Customizer, i.e. _if theme_mod equals something, add this particular CSS rule_. It's not designed to handle arbitrary user input.

There's actually a great tutorial over on WordPress.org for adding CSS boxes to the Customizer, and that is the approach I would recommend:
https://make.wordpress.org/themes/2015/02/10/custom-css-boxes-in-themes/
