### ISSUE TITLE
Header bar menu container is div, not nav

### ISSUE THREAD

**Issue by mattradford** [thethemefoundry/make#266]
Header bar menu is a nav, so should have a nav container, not div (IMO).

make/partials/header-layout.php & make/partials/header-layout-3.php

Alter wp_nav_menu from:

```
$header_bar_menu = wp_nav_menu( array(
    'theme_location'  => 'header-bar',
    'container_class' => 'header-bar-menu',
    'depth'           => 1,
    'fallback_cb'     => false,
    'echo'            => false,
) );
```

to:

```
$header_bar_menu = wp_nav_menu( array(
    'theme_location'  => 'header-bar',
    'container' => 'nav',
    'container_class' => 'header-bar-menu',
    'depth'           => 1,
    'fallback_cb'     => false,
    'echo'            => false,
) );
```

Whatever happened to header-layout-2? I feel cheated ;)

**Comment by scottrrollo** [comment]
Hello @mattradford!

> Header bar menu is a nav, so should have a nav container, not div (IMO).

Great suggestion. We'll get this sorted out.

> Whatever happened to header-layout-2?

Those numbers on the end just corresponds to the number of the layout option in the Customizer :).
