### ISSUE TITLE
WordPress oEmbed does not carry over from Builder Post Editor to Page

### ISSUE THREAD

**Issue by tonyzeoli** [thethemefoundry/make#269]
<img width="1268" alt="screen shot 2015-07-04 at 12 56 15 pm" src="https://cloud.githubusercontent.com/assets/4053819/8508767/1d0bf3c0-224c-11e5-9812-f39d1fd204da.png">
<img width="1265" alt="screen shot 2015-07-04 at 12 55 45 pm" src="https://cloud.githubusercontent.com/assets/4053819/8508768/1d1a0104-224c-11e5-9f98-da22ee66491a.png">

When I posted a YouTube video in the Builder Post Editor for a Column, the YouTube oEmbed displayed correctly in the Post Editor, but it does not carry over to the public facing page. Once I posted a link, it appeared as an oEmbed on the back end, but on the front end, it simply printed the link itself. The public facing page should support oEmbed, especially if it's available in in the Post Editor for any Builder template text entry fields.

**Comment by coreymckrill** [comment]
Hi @tonyzeoli,

Because of how the Builder renders and stores the section markup in the `post_content` field, the "naked link" method of embedding doesn't work on the front end. However, if you wrap the link in an embed shortcode, it should work. Example:

```
[embed]http://www.youtube.com/watch?v=dQw4w9WgXcQ[/embed]
```

**Comment by coreymckrill** [comment]
I'll leave this ticket open as a reminder to investigate ways to improve this in a future version.
