### ISSUE TITLE
White text doesn't display in the visual editor

### ISSUE THREAD

**Issue by melissajohill** [thethemefoundry/make#270]
If a user changes their text color to white, they cannot use the visual editor. I know it's pretty obvious why this is the case, but can something be done about it?

**Comment by scottrrollo** [comment]
Agree. I'd imagine the only time a user changes text color to white is when they have a dark background color or image added to the section. One idea would be to load this background into the editor itself.

**Comment by coreymckrill** [comment]
> One idea would be to load this background into the editor itself.

Unfortunately, I suspect this isn't possible in the Builder context, since we are using the same instance of the Editor for every content node on the page, each of which can potentially have a different background color.

**Comment by newlocalmedia** [comment]
Just stick with a black text color / do not load the custom colors ?
