### ISSUE TITLE
Social icons only appear when no menu is selected and disappear when their color is changed

### ISSUE THREAD

**Issue by dknauss** [thethemefoundry/make#271]
Social icons will not appear unless no menu is selected for them in the customizer. This is somewhat counterintuitive in an already confusing area with explanatory text.

Worse, with the "no menu" option in use for social icons, if you change the color of the icons in the customizer, they will all disappear from the customizer preview. To recover them, you have to go back to the social menu selector, select a menu, and then select the "no menu" --select-- option again.

![make](https://cloud.githubusercontent.com/assets/273554/8738404/66763ab4-2bf4-11e5-8b39-dffdd428d6c9.jpg)
(This is what the customizer settings should look like to display a LinkedIn icon linked to the URL shown.)

**Comment by coreymckrill** [comment]
@newlocalmedia thanks for the feedback. We've actually been discussing ways to make this UI easier to grok. Your input will definitely be considered.

Can you explain what you mean by changing the color of the icons? When I adjust the Header Bar text color with the social icons settings you're describing, the icons don't disappear...

**Comment by newlocalmedia** [comment]
I don't see this happen consistently in other environments using Make, so it may be a consequence of caching (W3TC with Memcached) active on the site where I'm seeing it.
