### ISSUE TITLE
Problems with buttons with text with multiple lines

### ISSUE THREAD

**Issue by drreen** [thethemefoundry/make#274]
Hey guys

When a ttf buttons' text has more than one line, the button looks faulty.
This is mostly the case on mobiile and when using buttons in tables, columns etc.
![bildschirmfoto 2015-08-01 um 08 20 01](https://cloud.githubusercontent.com/assets/2916173/9020868/21cd2cfe-3826-11e5-9d06-d23d9588f371.png)

adding
.ttfmake-button {
display: block ;
}
solved the issue

**Comment by scottrrollo** [comment]
Thanks for reporting this, @drreen! We'll be sure to look into this problem.

**Comment by jhaeger** [comment]
It seems to me that adding 

display:inline-block

Would solve it fairly elegantly.

**Comment by coreymckrill** [comment]
Deployed in 1.6.6
