### ISSUE TITLE
Background Size for Header in Customizer not accessible after making a selection

### ISSUE THREAD

**Issue by tonyzeoli** [thethemefoundry/make#279]
After selecting Size in Customizer > Background > Header, the section sort of moves down and the Size is no longer completely accessible. See the screenshot attached.

<img width="300" alt="screen shot 2015-08-20 at 10 51 44 pm" src="https://cloud.githubusercontent.com/assets/4053819/9400323/2ad4f8e6-478e-11e5-82f4-0ac089a805cb.png">

**Comment by coreymckrill** [comment]
Thanks for the report, @tonyzeoli . I suspect this is related to #277 because the _Size_ option shouldn't even be visible if an image hasn't been set yet.

**Comment by coreymckrill** [comment]
@tonyzeoli I believe that this was fixed in version 4.3.1 of WordPress. Can you confirm?
