### ISSUE TITLE
Uncaught TypeError when thumbnail support is removed from post type

### ISSUE THREAD

**Issue by glueckpress** [thethemefoundry/make#281]
I’ve registered builder support for a custom post type:

```php
add_action( 'admin_init', function () {
	add_post_type_support( 'foo_post_type', 'make-builder' );
} );
```

When my custom post type does _not_ support featured images (`thumbnail`), I’ve noticed a JavaScript error that prevents editing/toggling of builder sections:

```
Uncaught TypeError: Cannot read property 'view' of undefined    app.js:279
```

Just to be safe, I’ve tried to replicate the behavior for pages with 

```php
add_action( 'init', function () {
	remove_post_type_support( 'page', 'thumbnail' );
} );
```

Result: the very same error.

My JavaScript sort of sucks, so I haven’t tried to dig into that error. Any ideas how to fix this would be highly appreciated.

**Comment by coreymckrill** [comment]
@glueckpress Interesting. Looks like there's a necessary core script missing when featured images aren't enabled. Try this:

In **inc/builder/core/base.php**, find [this](https://github.com/thethemefoundry/make/blob/1.6.3/src/inc/builder/core/base.php#L251-L259), and add an additional item to the array: `'media-views'`

FYI, the functionality for adding the Builder to other post types besides pages is not complete, as you can see from bugs like this. We don't officially support it right now, and I wouldn't recommend using it on a client site.

**Comment by glueckpress** [comment]
Thanks, @coreymckrill, I’ll try that. Needless to say, imho custom post type support would add a lot of value to the Make (or to Make plus). :wink: So far my little experiment is going pretty well, though, besides the behavior described above. Very neat product.

**Comment by coreymckrill** [comment]
Deployed in 1.6.6
