### ISSUE TITLE
Linked headings in content don't exhibit the correct link color

### ISSUE THREAD

**Issue by coreymckrill** [thethemefoundry/make#282]
https://thethemefoundry.com/questions/topic/headlines-with-link-no-link-colortext-decoration/

**Comment by scottrrollo** [comment]
This is intentional. I'd imagine many users don't want to see bold heading tags in the same color as their content links. We could consider adding a separate color picker to the Customizer for **header links within content**.

Replacing **bug** label for **enhancement**.
