### ISSUE TITLE
Long list items with a custom icon wrap instead of display flush left

### ISSUE THREAD

**Issue by scottrrollo** [thethemefoundry/make#283]
Example from customer site:

<img width="640" alt="screen shot 2015-09-17 at 3 36 45 pm" src="https://cloud.githubusercontent.com/assets/1041614/9925716/f147077a-5d51-11e5-8891-f899a63413cc.png">

**Comment by coreymckrill** [comment]
I'm not aware of a way to change this when using custom icons for the bullet points...
