### ISSUE TITLE
Builder changes Underscore's global template eval settings, breaks other scripts using it

### ISSUE THREAD

**Issue by coreymckrill** [thethemefoundry/make#293]
This came up because the Builder is breaking some of the functionality in the ACF plugin.

From an email conversation with the user who discovered it:

> It is caused by Make changing the default template settings for the _ (underscore.js) template utility. See line 36 of inc\builder\core\js\views\section.js. There, Make changes the default _.templateSettings to use <#= #> for evaluation. However, ACF uses the default <%= %> format. I'm guessing the best solution would be for Make to not overwrite the page-global underscore.js defaults...

**Comment by tollmanz** [comment]
@coreymckrill This was done for good reason. The `<%` tags can be interpreted as PHP tags (e.g., `<?`) on some systems. This is a PHP configuration option. When we initially released Collections, we used `<%` and it caused fatal error for some users. Perhaps there is a way to do this more responsibly, but if you change to the default, fatal errors *could* occur.

**Comment by coreymckrill** [comment]
@tollmanz thanks, I was thinking it was something like that. Maybe there's a way to set the eval tags on a per-case basis instead of globally. Or, I may have to dig into ACF's code to see how they are handling that same situation (maybe they're not?)

**Comment by dpfavand** [comment]
Thanks @coreymckrill and @tollmanz for looking into this - the PHP conflict explanation is very helpful. When I was trying to find the issue, I noticed in the underscore.js documentation that the _.template() function accepts an optional settings parameter that overwrites the default _.templatesettings http://underscorejs.org/#template - perhaps that would be a way for Make to avoid the PHP issue while not conflicting with other plugins?

And/or, perhaps ACF's use of underscore templates should be changed to be safer on some PHP configs, although that wouldn't solve the potential conflict with other plugins.

As far as I can tell, ACF only uses _.template() in one place, though I might have missed something.

ACF's use of _.template() is here: https://github.com/elliotcondon/acf/blob/e8fef3a78248cff2b61b419964652177311325cb/js/input/relationship.js#L219
Which ends up concatenated with other scripts into this file, which is minified for the release: https://github.com/elliotcondon/acf/blob/master/js/input.js#L3107

The template ACF uses is defined here: https://github.com/elliotcondon/acf/blob/e8fef3a78248cff2b61b419964652177311325cb/core/fields/relationship.php#L30

Thanks again.

**Comment by tollmanz** [comment]
One potential resolution is for Make and ACF to use `wp.template`, WordPress [utility for Underscores templates](https://github.com/WordPress/WordPress/blob/master/wp-includes/js/wp-util.js#L17-L36). This is not well documented, but for 3rd party code to best ensure compatibility with WordPress, it would be best to use WordPress' standard for templating. Admittedly, I did not do this when implementing the template in Make (not sure exactly why not), but was aware of the conflict issue. At a minimum, I think that 3rd party code should avoid using `<%` given the potential fatal error.
