### ISSUE TITLE
4.4 compatibility

### ISSUE THREAD

**Issue by coreymckrill** [thethemefoundry/make#295]
Collector for issues and things to test for the upcoming release of WordPress 4.4.

* [x] Builder interface (style issues) @scottrrollo 
* [x] Customizer interface @scottrrollo

**Comment by coreymckrill** [comment]
@scottrrollo ^ This commit sort of fixes the Builder UI issues, but there is extra padding on the section toggle, and the section toggle is now broken on versions prior to 4.4. (At least, in Firefox)

4.4:
![4 4-beta](https://cloud.githubusercontent.com/assets/916023/11228629/d2ca876a-8d42-11e5-9c0a-5e6fa287c051.png)

4.3.1
![4 3 1](https://cloud.githubusercontent.com/assets/916023/11228631/dc723b8c-8d42-11e5-9b8a-0994f2cebb7d.png)

**Comment by scottrrollo** [comment]
@coreymckrill Are you using the *WordPress Beta Tester* plugin, or the 4.4 Beta 4 .zip?

**Comment by scottrrollo** [comment]
@coreymckrill I cannot recreate what you're seeing using WordPress 4.4 Beta 4 in Firefox 42.0 on the `wp-4-4` branch.

**Comment by scottrrollo** [comment]
@coreymckrill I decided, like you suggested, to roll our own section toggle. The change replaces `handlediv`.

In my test, the new toggle is looking great in Safari, Chrome and Firefox, using 4.4 and 4.3.1. 

Could you please also review these changes?

**Comment by coreymckrill** [comment]
@scottrrollo looks good to me. Do these changes apply to anything besides the toggle button on the Section header bar?

**Comment by coreymckrill** [comment]
@scottrrollo Also, for the second item on the checklist above, here is what I'm seeing for our Customizer buttonset controls in 4.4:

![buttonset](https://cloud.githubusercontent.com/assets/916023/11259043/3d2680ca-8e13-11e5-88d3-1cf5f8ae1997.png)

**Comment by scottrrollo** [comment]
>  Do these changes apply to anything besides the toggle button on the Section header bar?

@coreymckrill No, that's all.

**Comment by scottrrollo** [comment]
> …here is what I'm seeing for our Customizer buttonset controls in 4.4.

@coreymckrill I don't mind that, actually. What do you think? I can tidy it so the borders are consistent.

**Comment by scottrrollo** [comment]
@coreymckrill OK, buttonset controls are all patched up. I decided to clean up the borders and display the buttons inline. Please let me know if you notice any problems.

**Comment by coreymckrill** [comment]
@scottrrollo Buttonsets look good! Let's leave this ticket open until 4.4 is released in case anything else comes up.
