### ISSUE TITLE
Make Breakpoints more accessible

### ISSUE THREAD

**Issue by kirstenschelper** [thethemefoundry/make#296]
I love Make and I managed to do almost everything my client needed with Make. With one exception: The breakpoints.

The breakpoints are stored in variables ($one, $two, $three) deep down in the SASS system. Theoretically I can overwrite them, but practically this doesn't work. As all the CSS depends on those variables I would have to output all the CSS once more AFTER I changed the variables.
This makes no sense.

I wish the breakpoints would be set in a more accessible manner. 
Perhaps not in a variable, but as simple media queries. 

Example: The bones theme does it quite nicely, I think. 
https://github.com/eddiemachado/bones

The method is very simple. The CSS for the breakpoints is stored in different modules (for example 1030up.scss). These modules are called wrapped in "open" media queries in the **main SASS file** (style.scss).
So everything is open and accessible and keeps being nicely modularized.

@media only screen and (min-width: 1030px) {

```
// styles in 1030up.scss
@import "breakpoints/1030up";
```

} // end of media query

**Comment by scottrrollo** [comment]
Thanks, @kirstenschelper! It's great to get your feedback! We have big plans to make the stylesheets easier to work with.
