### ISSUE TITLE
Add do_actions to the templates

### ISSUE THREAD

**Issue by BoweFrankema** [thethemefoundry/make#297]
Hi ThemeFoundry Team,

Thanks for creating an awesome theme with Make. I do have one pretty serious complaint.. For the life of me I can't understand why you haven't added do_actions to the theme. This makes it very hard to customise the theme without overwriting a lot of templates. Is this on the roadmap?

**Comment by coreymckrill** [comment]
@BoweFrankema thanks for the feedback. This is, indeed, on the roadmap. We haven't settled on a plan for this yet, but are considering a convention similar to [Theme Hook Alliance](https://github.com/zamoose/themehookalliance).

**Comment by helgatheviking** [comment]
:+1: for Theme Hook Alliance.
