### ISSUE TITLE
When using shortcodes in columns, a great deal of whitespace is added all the way to footer

### ISSUE THREAD

**Issue by tonyzeoli** [thethemefoundry/make#299]
Hi,

I'm trying to use 8tracks.com and Mixcloud.com shortcodes in Builder columns. When I added the shortcodes, a ton of whitespace was added below the columns and you have to scroll a great deal to get to the footer.

See the example here: http://netmixcom.staging.wpengine.com/netmix/

**Comment by coreymckrill** [comment]
@tonyzeoli it looks like that extra space is caused by the height that is getting set on the MixCloud iframe. Where does that shortcode come from? Jetpack?

**Comment by tonyzeoli** [comment]
The shortcode comes from MixCloud, before MixCloud was adopted as an oEmbed in JetPack. I was using it because of the options it provided, but when I do away with the height option, it does work fine as on the live homepage of netmix.com. So, I think it's just that use case. I'm gonna say that it's probaby not a big deal, because most people would use the oEmbed, however, you can't use oEmbed in a Make column text field yet - or, at least I think you can't.

**Comment by coreymckrill** [comment]
I believe oEmbed URLs can be recognized in the Builder by wrapping them in an embed shortcode:

```
[embed]http://mixcloud.com/my/url[/embed]
```

**Comment by tonyzeoli** [comment]
Ah, okay. I will try that next time. We can close this is fine. I'll just
use that method.
