### ISSUE TITLE
Typo in Dutch translation?

### ISSUE THREAD

**Issue by coreymckrill** [thethemefoundry/make#301]
From a customer email:

> there is the Dutch word “jou”. This word has to be “jouw”. Then it is correct Dutch.

It is referring to [this translation string](https://github.com/thethemefoundry/make/blob/1.6.7/src/partials/content-none.php#L19).

Thoughts, @LeoOosterloo ?

**Comment by LeoOosterloo** [comment]
That is correct. 'jou' should be 'jouw'.

**Comment by coreymckrill** [comment]
Thanks @LeoOosterloo . Fixed!
