### ISSUE TITLE
makeplus_postslist_query_args filter doesn't filter builder section

### ISSUE THREAD

**Issue by mrwweb** [thethemefoundry/make#302]
In testing 1.7-beta, I received the notice that `ttfmp_post_list_query_args` was deprecated. I switched to use the `makeplus_postslist_query_args` as directed by the Make Error (I love that, btw) and my filter no longer worked.

From `functions.php`, here's what I had:
```php
add_filter( 'makeplus_postslist_query_args ', 'pc_filter_make_post_list', 20, 2 );
function pc_filter_make_post_list( $args, $options ) {
	// the page we're on...
	$exclude_me = get_the_id();
	// ...yeah, don't show that
	$args['post__not_in'] = array( (int) $exclude_me );

	return $args;
}
```

Looking in `/make-plus/inc/component/postslist/setup.php`, it seems to take the exact same parameters as before. However, after poking around a bit more, unless I'm missing something (which is very possible, so take this with a grain of salt), the `build_query()` method that contains the `makeplus_postslist_query_args` filter only gets used by the shortcode and not the builder section. Whatever the cause, my filter was working and now it isn't.

**Comment by coreymckrill** [comment]
Hey @mrwweb !

Hmm, the Builder section just outputs the shortcode with all the parameters. Maybe try hitting _Update_ on your Builder page to refresh the markup?

**Comment by mrwweb** [comment]
Glad to better understand how that works with the shortcodes. Updating didn't fix it though :(

**Comment by coreymckrill** [comment]
"Isn't working" means the current post is being included in the Posts List, right?

Two questions:

* If you switch back to the deprecated hook name, does it work again?
* What other parameters do you have set for that particular Posts List? (if you temporarily switch back to the "Default" page template you can see the underlying shortcode. Might be easiest to just paste that here).

**Comment by mrwweb** [comment]
> "Isn't working" means the current post is being included in the Posts List, right?

Correct.

> If you switch back to the deprecated hook name, does it work again?

It doesn't. However, I had a `var_dump()` in my copy of the filter function and enabling the old filter *did* suddenly make the `var_dump()` results appear. Previously, they hadn't.

> (if you temporarily switch back to the "Default" page template you can see the underlying shortcode.

`[ttfmp_post_list columns="3" type="page" sortby="date-desc" keyword="" count="6" offset="0" taxonomy="postid:58" show_title="1" show_date="0" show_excerpt="0" excerpt_length="55" show_author="0" show_categories="0" show_tags="0" show_comments="0" thumbnail="top" aspect="square"]`

**Comment by coreymckrill** [comment]
Admittedly, I'm pretty baffled. The changes to Posts List in the 1.7 beta are pretty minor. I haven't reproduced this yet, but will keep working on it next week...

**Comment by mrwweb** [comment]
Color me equally confused. The `var_dump` thing is especially perplexing. I'm not sure how I can make the test-case any simpler, but if you have ideas let me know. There's also a small chance (probably not) that this is a byproduct of #303.

**Comment by coreymckrill** [comment]
@mrwweb I tried adding your exact code snippet from the beginning of this thread, and it also wasn't working for me. I noticed that there was an extra space after the end of the hook name, and once I removed that, the filter worked for me. I'm not sure how that would explain the whole `var_dump` thing, but try removing that extra space and see if that helps.

**Comment by mrwweb** [comment]
Wow. The space was totally it. I am so sorry for yanking you around on that wild goose chance. Thanks for helping me figure that one out.
