### ISSUE TITLE
Breaking changes in 1.7.0 beta 1

### ISSUE THREAD

**Issue by johnjamesjacoby** [thethemefoundry/make#304]
There are numerous breaking changes in the 1.7.0 beta, and no public repository to send upstream pull requests to. While some of these changes seem intentional (though, unnecessary IMO) there are several blockers that make 1.7.0 (ha!) impossible to use without modification.

Where do we send pull requests?

**Comment by johnjamesjacoby** [comment]
I think I understand now. The `develop` branch is where 1.7.0 dev is happening. I'll close this, switch to that, and start with issues and helping where I can. <3

**Comment by coreymckrill** [comment]
@johnjamesjacoby Happy to take PRs to the `develop` branch. It would be helpful if you could open issues for specific blockers, too.
