### ISSUE TITLE
Header bar text not vertically aligned when search/social icon elements are disabled

### ISSUE THREAD

**Issue by pmgarman** [thethemefoundry/make#306]
Disable the search field and social icons, and the header bar text will have no top margin/padding making it not vertically aligned in the center, which looks awkward.

![](http://c.pmgr.mn/16hd1+)

This is on 1.7 beta 1, but can only imagine is valid also in 1.6.x

**Comment by pmgarman** [comment]
Additionally - the padding in the customizer is not the same as the padding shown on the live site.

![](http://c.pmgr.mn/17E4q+) vs ![](http://c.pmgr.mn/19ll4+)

**Comment by coreymckrill** [comment]
Thanks @pmgarman . We'll take a look. We also take pull requests on the `develop` branch if you want to take a crack at it.
