### ISSUE TITLE
Custom logo not scaling correctly in IE

### ISSUE THREAD

**Issue by coreymckrill** [thethemefoundry/make#312]
As reported by a user, the custom logo is not respecting CSS width rules.

Example in Firefox:

![custom-logo_ff](https://cloud.githubusercontent.com/assets/916023/15373052/1e917ad6-1cf0-11e6-8e34-db65548f0107.png)

Same site in IE:

![custom-logo_ie](https://cloud.githubusercontent.com/assets/916023/15373055/2467f2a0-1cf0-11e6-8cc0-66b05f1e30da.png)

I can confirm that this happens on our demo site in IE as well.

**Comment by scottrrollo** [comment]
@coreymckrill Fix committed to `develop`. Marking **needs deploy**.

**Comment by coreymckrill** [comment]
Confirmed that this fixes it on IE for me! Thanks @scottrrollo

**Comment by scottrrollo** [comment]
Deployed. Closing…
