### ISSUE TITLE
Current menu item is bold regardless of Customizer settings

### ISSUE THREAD

**Issue by scottrrollo** [thethemefoundry/make#314]
A current menu item is shown by a bold font weight. Switching the **Typography &rarr; Main Menu &rarr; Current Item** setting to **Normal** does nothing.

@coreymckrill Is this something we could add to our next release?

**Comment by coreymckrill** [comment]
73c91476de3c410b7716c1bf7ecb2849526e45d1

**Comment by coreymckrill** [comment]
@scottrrollo can you confirm that the above commit fixes the issue?

**Comment by scottrrollo** [comment]
@coreymckrill Looks perfect 👍

**Comment by coreymckrill** [comment]
Deployed.
