### ISSUE TITLE
Widget Body Color does not apply to a widget hosted in a colum

### ISSUE THREAD

**Issue by tonyzeoli** [thethemefoundry/make#319]
If the page uses the default template and contains a sidebar, the Widget Body Color is inherited if changed in the customizer.

If the page uses the page builder and you add a widget to a column, the Widget Body Color does not affect the widget area.

See: https://totmerchres.staging.wpengine.com/business-financial-solutions/

I've set the widget body color in the customizer to #857672 and it does not change the color of the text for the widget assigned to the column, but it does change it if it's in a sidebar.

**Comment by coreymckrill** [comment]
Hi @tonyzeoli!

This is actually the intended behavior. Widgets in the Columns widget areas are handled and styled like the rest of the content in the main content column. That's why in both the Color and Typography panels in the Customizer there are sections for styling "Sidebars" but not for widgets in general.

**Comment by tonyzeoli** [comment]
Okay, that was not clear to me. I will say that you're forcing the design
to apply the same styles to all columns, when that may not work and boxes
in the designer from using the Make tools to manage design across in the
columns area. If the designer wants to break from the design, sure, they
can write child styles and override, but it would helpful to not force the
designer to say that every column in a column section should only use the
styles from the column section. Because I can't use a sidebar with page
builder, I lose the ability to style my widget different than if it's
thrown into the column section. I ask you guys to think about that and
allow me to adopt a widget style in a column that was assigned in the
sidebars and widgets area. That would give me the ability to differentiate
the sidebar style from the column style. Hopefully, you'll agree that
should be an option and I shouldn't be locked into one or the other, which
I am not simply because I cannot use a sidebar with page builder.
