### ISSUE TITLE
Post list widget title shows escape characters

### ISSUE THREAD

**Issue by newlocalmedia** [thethemefoundry/make#323]
Using apostrophes in the widget title of a post list widget results in a visible slash being added ahead of the apostrophe.

**Comment by coreymckrill** [comment]
@newlocalmedia I'm not seeing the escape slashes when I try this. Is this in one of the standard right/left sidebars, or somewhere else?

**Comment by coreymckrill** [comment]
Also, is this with the most recent version of Make Plus?

**Comment by newlocalmedia** [comment]
Yes it is. It's the Make Plus Posts List widget assigned to a Make page layout. When a title with an apostrophe is saved from the page layout, the slash appears -- but not when the Widget manager interface is used.

**Comment by coreymckrill** [comment]
Ah, I see it now. Looks like it's only happening with the Posts List widget, not other widgets with title fields...

**Comment by coreymckrill** [comment]
Alright, I think I have a fix. Can you go to **inc/component/postslist/setup.php** in the Make Plus plugin folder, and find this on line **276**:

```php
$clean_data['title'] = $clean_data['label'] = apply_filters( 'title_save_pre', $parsed_data['title'] );
```

... change it to this:

```php
$clean_data['title'] = $clean_data['label'] = sanitize_text_field( $parsed_data['title'] );
```

... and let me know if that fixes the issue. Note that won't remove an existing backslash, but it should prevent them from getting added next to apostrophes.
