### ISSUE TITLE
Make Plus 1.7.4 making 123 queries, causing 502 timeouts in Pages admin

### ISSUE THREAD

**Issue by tonyzeoli** [thethemefoundry/make#332]
Hey Cory,

I've recently installed Make Plus 1.7.4 on my WordPress install for neighborbeeblog.com at WP Engine. I've gone through a slew of testing (turning on twenty sixteen, issue went away; disabling all plugins, issue persists) and have really come down to the culprit being the Make Plug 1.7.4 version of the plugin that is causing insane amount of slowness, to the point I can't edit anything. It's crushing me on this project and I'm not sure what to do about it.

Here's the thread on Theme Foundry Help forums: https://thethemefoundry.com/questions/topic/page-builder-slow-to-load-panels-and-change-settings/#post-66030

At the bottom of the thread, you'll see that WP Engine ran a query test and came up with 123 queries coming from Make Plus. This site has about 800 posts, so I'm not sure if that has something to do with it, but all my research is in the help desk post and you'll see the time out error in the WP Engine error log and the screenshot from them showing how many queries Make Plus is making as opposed to the only other plugin, AIOSEO pack only making 3.

I hesitate to upgrade to Make Plus on any of my other installs until this is fixed.

This is a very serious issue for me. I bet the farm on Make with my client and his expectation is that it works with no issues. Now, I'm not so sure where this is coming from and why and it's really stressful. I need someone to please help asap. I have all my clients on Make and Make Plus and if this happens everywhere, it could set me back considerably.

**Comment by scottrrollo** [comment]
Hey @tonyzeoli! That sounds like a real nuisance and so sorry to hear the cause might be our latest version of Make Plus.

I've emailed Tom and Ignazio about this, and when they get online (in about an hour from now) we'll do our absolute best to get to the bottom of this. Promise.

Hold tight and hopefully we'll have good news for you soon 😄 

By the way, I'll close out this issue and we'll keep the conversation going in the support thread you've already started.

**Comment by tonyzeoli** [comment]
Thanks, Scott.
