### ISSUE TITLE
Add support to change mobile menu background color and font color in Customizer

### ISSUE THREAD

**Issue by tonyzeoli** [thethemefoundry/make#341]
If you can manage a button color in the Customizer, you should be able to manage your mobile menu background color and font color in the Customizer as well. Yes, I've posted to the forum and that I can add a CSS rule for .menu-toggle, but there is always a use case to change the background color of the mobile menu nav bar and I just feel that it should be something anyone can set in the Customizer. I hope this can be adopted, so non-developers who use Make can make the change without having to find where this is in using developer tools, because it's not that easy to find. It could take an hour for someone to figure out if .menu-toggle is the right target. Or, they have to write in and waste a day cycle waiting for someone to respond in support with the answer, when it can really just be added and that's that. :)

**Comment by scottrrollo** [comment]
@tonyzeoli Thanks for sharing! We'll be sure to look into working this into a future release.
