### ISSUE TITLE
Customizer Button Background Color will not chance background color if set in Format Builder

### ISSUE THREAD

**Issue by tonyzeoli** [thethemefoundry/make#342]
If you make a button background color with the Format Builder in the body of a page builder section, then try to change the global background color in the Customizer, the button background color does not update.

But, if you set a Global button background color in the Customizer, then create a button, you can see the colors you previously set.

Does that make sense?

**Comment by scottrrollo** [comment]
@tonyzeoli Makes complete sense! I see this and your other report as related, so I'll link the two and close this one. Thanks!
