### ISSUE TITLE
Add Button Styling Options in Format Builder to Customizer

### ISSUE THREAD

**Issue by tonyzeoli** [thethemefoundry/make#343]
It's odd that I can set the background color, hover color, and text colors, but I can't set anything else from the Format Builder for Buttons in the Customizer. If I want all buttons globally to be consistent, I should be able to do that in the Customizer. Why I only have the options in the Format Builder, I don't know. Especially if something like a Gravity Forms button can take on the Global style of a button. Then I don't have to use CSS to style it the exact same way as Make Format Builder Buttons.

**Comment by scottrrollo** [comment]
@tonyzeoli Good points 👍 We're working to make this easier.

**Comment by scottrrollo** [comment]
Also see: https://github.com/thethemefoundry/make/issues/343#issuecomment-275517453

**Comment by tonyzeoli** [comment]
Thanks!

**Comment by sixFingers** [comment]
@tonyzeoli 👍  good point! You can't currently override a Make button style through CSS because our Format Builder prints your color configuration in the button tag's style attribute:

```
<a id="ttfmake-1485510303" class="ttfmake-button" style="background-color: #ff0000; ..."></a>
```
