### ISSUE TITLE
Some H5 and all H6 controls do not display in customizer

### ISSUE THREAD

**Issue by tonyzeoli** [thethemefoundry/make#344]
I'm having this odd issue.

When I go into Customizer to work with H5 and H6 rules, the selectors do not display.

Here's a screenshot: https://cloudup.com/cgVN75u7pn4

**Comment by sixFingers** [comment]
@tonyzeoli Would you inspect the H5 and H6 elements, and see what styles are being applied to them?

**Comment by tonyzeoli** [comment]
For the H5, I have it set to Oswald (before the options disappeared) with some styles as shown in the screenshot.
[](https://cloudup.com/crtcAuHKs8u)

The H6 is set to Helvetica with some styles being applied to it as shown in the screenshot.
[](https://cloudup.com/cyRCmfpLCRM)

**Comment by tonyzeoli** [comment]
Here's a link to the body of the post if you need to inspect any further: https://savethegreatsouthbay.org/2017/01/03/menhaden-management/

See the two "Test" words at the bottom of the post.
