### ISSUE TITLE
Set background color for banner does not take

### ISSUE THREAD

**Issue by tonyzeoli** [thethemefoundry/make#345]
Tried setting a background color for banner, but background is grey when set color is light blue.

See the chooser here for Banner Background Color

https://cloudup.com/cjU7lFAyAzK

See the page here when the background color is set to light blue.

https://cloudup.com/ckoqBuopyjX

The grey bar appears but does not change color. If I remove/reset background color for banner, turns to white and no longer an issue. But if I had a light blue header and wanted to continue the blue color from header to background behind the banner, I wouldn't be able to do that based on this bug.

**Comment by scottrrollo** [comment]
Hey @tonyzeoli 👋 So you're seeing this muted color because the **Darken to improve readability** option is checked. Try unchecking that and you'll see the color you're after. 😀

**Comment by tonyzeoli** [comment]
Sorry I didn't follow back up on this. I'll take a look.
