### ISSUE TITLE
Column section will not create a new section instance with Make Plug enabled

### ISSUE THREAD

**Issue by tonyzeoli** [thethemefoundry/make#347]
Hi,

I'm using Make (1.8.7) and Make Plus (1.8.2)

- When Make Plus is active, the column button in builder DOES NOT create new column sections.
- When I disable Make Plus, the reverse is true. I CAN create column sections with the column button in builder.

This bug is occurring in a WordPress network on staging at WP Engine

http://netmixcom.staging.wpengine.com/digitalstrategyworks

I cannot use builder to add a column section, so have disabled Make Plus until their is a fix.

**Comment by tomasstark** [comment]
Hey Tony!

Would you mind updating Make Plus to latest version? We introduced a lot of under the hood changes to Columns in Make and Make Plus 1.8.3. Since you're on Make Plus 1.8.2, with Make being on latest version, it's likely Plus not keeping up.

Hope this helps! 🙂

**Comment by tonyzeoli** [comment]
Ah, okay. I am not seeing the Make update notification for 1.3 in my Plugins page.

Probably why I didn't know about it.

Screenshot: https://cloudup.com/cLML8NA9EMK:

**Comment by tonyzeoli** [comment]
Now I see that the Make download from my Account page is at 1.8.5. Please note that updates are not displaying in the Plugins admin page in WordPress for me. I'm downloading and installing manually, but others may have this problem.

**Comment by tomasstark** [comment]
Closing this out as it's Make Plus related and already being discussed [on our forum](https://thethemefoundry.com/questions/topic/wordpress-plugin-admin-does-not-indicate-an-update-is-available/).

Thanks for reporting this, Tony! 🙂
