### ISSUE TITLE
WordPress Link editor drop down text hidden by white background

### ISSUE THREAD

**Issue by tonyzeoli** [thethemefoundry/make#354]
Hi,

I'm not sure if this is a Make bug or something else, but recently after updating Make and Make Plus, I'm seeing this issue in the link editor, where the drop down displays a white background hiding a subset of link text options, then past a certain point, the reverse is true where a black background displays white link text options. Here's a screenshot: https://cloudup.com/cGfM-DhsEm0

You have to rollover the first few link(s) text to actually see the page or post you're looking for to link to.

**Comment by scottrrollo** [comment]
Hey there, @tonyzeoli 👋 

That's not something we've seen before. Our hunch is a plugin (or maybe a browser extension) is throwing those drop-down styles out. Would you mind seeing what happens if you disable your plugins?

Let us know what you find out!
