### ISSUE TITLE
Z-index of Column controls needs to clear admin sidebar

### ISSUE THREAD

**Issue by tonyzeoli** [thethemefoundry/make#355]
The column control pop up seems to fall under the left side WordPress Dashboard admin bar. Can't read the menu items because they are impacted by falling underneath the left admin bar.

See the screenshot: https://cloudup.com/c4F3xHrhyPJ

**Comment by scottrrollo** [comment]
Thanks for the heads-up, @tonyzeoli! I can see this too. We'll be sure to look into this.

@tomasstark @sixFingers Do you think we can work this into our latest release please?

**Comment by tomasstark** [comment]
Sure thing! We'll look into it. Thanks for reporting this, @tonyzeoli!

**Comment by tonyzeoli** [comment]
No problem - love what you're all doing to create an awesome theme framework and page builder tools. My pleasure to report things when I see them. It's my responsibility to help where we can as a participant in these communities.
