### ISSUE TITLE
Text Color for Menu does not override option in Site Header

### ISSUE THREAD

**Issue by tonyzeoli** [thethemefoundry/make#356]
Trying to set the text color setting under the Menu option will not override the Site Header color setting. Select a color with color picker and nothing happens. Still same color as Site Header selection.

**Comment by tonyzeoli** [comment]
Oh, wait...I had to navigate to another option and then click save for the text color for the menu to change. Maybe it's not that it doesn't change, it's that it doesn't immediately change when you use the color picker to initially make the selection.

**Comment by scottrrollo** [comment]
@tonyzeoli Thanks for posting this! Honestly, it sounds like a customizer quirk. Sometimes the customizer doesn't like to update as quickly as it should.

It's working here so I'll close this ticket. If things continue to play up, let us know 😀
