### ISSUE TITLE
1.9 version has broken website

### ISSUE THREAD

**Issue by tonyteehee50** [thethemefoundry/make#357]
Update to 1.9 earlier has caused page builder to stop operating. Unable to create or edit pages using the page builder and all pages that have been build with page builder have reverted to wordpress default pages, Running child theme and make plus plugin

**Comment by scottrrollo** [comment]
@tonyteehee50 I know we reached you on our social channels, but just in case, be sure to upgrade to Make Plus 1.9. That's should do the trick.

Let us know how you go!

**Comment by tonyteehee50** [comment]
Yes upgraded and all is back to normal. Heart has stopped racing and underpants in the wash.

Tony

**Comment by scottrrollo** [comment]
Sorry for the panic, @tonyteehee50! Glad to hear it's all working now.

Let us know if there's anything more we can help with 😄

**Comment by tonyteehee50** [comment]
Well I thought everything was working fine but no it isn't.
My About page has lost its widget are which was a customised column changed to widget area. Now the Widget page where all the widgets show still has this widget area but my About page will not show it or even allow me to create a new one. Something has gone awry. Any ideas what is happening?
Tony Walker 

    On Tuesday, 15 August 2017, 22:57, Scott Rollo <notifications@github.com> wrote:
 

 Closed #357.—

**Comment by scottrrollo** [comment]
@tonyteehee50 Let's track down the cause of this in #361

**Comment by tonyteehee50** [comment]
Try #362
Still not working properly
Tony 

    On Thursday, 17 August 2017, 23:15, Scott Rollo <notifications@github.com> wrote:
 

 @tonyteehee50 Let's track down the cause of this in #361—

**Comment by tomasstark** [comment]
@tonyteehee50 We released Make 1.9.2 and Make Plus 1.9.3 today. Would you mind giving it a try and see if it works?

**Comment by tonyteehee50** [comment]
I have it running check http://midlothiancamera.org.
seems to have solved the problem. The site is not finished by a long way. just a skeleton for club to put content on
I know GITHUB isn't always the best forum but I just don't want others suffering the same fate. Added everything I was doing so you knew what was tested. I was about to take all the CSS I have created off in case I had done something but it all worked prior to 1.9. Then the update came. It had to be something not reading the media queries. I am learning to develop themes but wow yours is big and daunting for a beginner
Can you confirm for me if I deactivate Makeplus then reactivate it again should it be wiping all my widgets. which is what's happening.
I know Make doesn't include column being converted to widgets but surely if no changes are made to Make or in my case a child theme the widgets should remain and not be wiped out. It doesn't take long to reinstate them but it's a bit of a bind.
Or is it something else I have found....


Thanks again
Tony 

    On Tuesday, 22 August 2017, 12:32, Tomas Stark <notifications@github.com> wrote:
 

 @tonyteehee50 We released Make 1.9.2 and Make Plus 1.9.3 today. Would you mind giving it a try and see if it works?—
