### ISSUE TITLE
Widget areas.

### ISSUE THREAD

**Issue by tonyteehee50** [thethemefoundry/make#361]
It's actually worse. All widget areas have been removed on my site with this update and unable to create new ones

**Comment by scottrrollo** [comment]
@tonyteehee50 Sorry to hear about this! I'll loop @tomasstark and @sixFingers into this conversation. We'll look into this issue and get back to you as quickly as we can with an answer!

**Comment by tonyteehee50** [comment]
I'm running Make theme with Makeplus and a child theme.
Since 1.9 upgrade all widget areas were removed. They remain in the widget area with no widgets attached.
On checking some of my pages the widget area is there in the customiser and have been able to reactivate them by adding widgets to them. 
Other widget areas which are also in the widget area will not show up in the customiser for the given page. i can create a new widget area but on saving it does not appear either.
If I create a brand new page with say three columns and I convert the third one to a widget area it does this. When saved and or publish this widget area fails to show for the page in the customiser as it used to. It is there in the page set up but not in front end or customiser.

Very strange behaviour. its like some of the makeplus is working and other parts not. Either that or it is not liking the child theme any more. I'm left scratching my head

**Comment by tonyteehee50** [comment]
updated to 1.91 on both make and make plus. Still no joy. Widget area created and goes into widget area. However go to customiser  and it isn't there so unable to add widgets to it.

**Comment by tonyteehee50** [comment]
ok 1.9.2 has fixed the wigetised problem. For users you will need to remove the wigetised area back to a normal column. Then reconvert it back to a wigetised area and update,then populate through the customiser.

**Comment by tomasstark** [comment]
@tonyteehee50 Apologies for a late reply, I was just about to post an update here. As you already noticed, we released 1.9.2 today, patching this issue up.

Thanks for reporting this! 👍
