### ISSUE TITLE
Fontawesome resources missing

### ISSUE THREAD

**Issue by robertomarchena** [thethemefoundry/make#366]
In the most recent update, the following files seem to be missing under
/make/css/libs/font-awesome/fonts causing fontawesome symbols not working (e.g. hamburger menu icon)

fontawesome-webfont.woff2
fontawesome-webfont.woff
fontawesome-webfont.ttf
fontawesome-webfont.svg
fontawesome-webfont.eot
FontAwesome.otf

**Comment by scottrrollo** [comment]
Thanks for reporting this, @robertomarchena! 

@tomasstark @sixFingers Would you please look into this?

**Comment by tomasstark** [comment]
Hey @robertomarchena! 

We upgraded Font Awesome version to the latest v5 (previously Make used v4). There are quite a few changes in v5, including [new font files](https://github.com/thethemefoundry/make/tree/master/src/css/libs/font-awesome/fonts) which replaced the ones you listed.

That being said, I have a hunch that the issue you have is related to cache. Would you mind refreshing your page a couple of times and see if it helps?

Thanks!

**Comment by robertomarchena** [comment]
Thanks for the info. After looking into this again, there was indeed an odd (server-side) caching issue. I updated a couple of other sites which worked just fine now.

Besides this Github rep, is there actually a change log available somewhere? That would make it easier to anticipate these kind of issues.

**Comment by greenweb** [comment]
Just had a client ask me about it today, dumping the site's cache didn't help, any other ideas?

**Comment by tomasstark** [comment]
@greenweb It's most likely browser's cache actually. Would you mind advising your client to flush browser's cache, trying it in a browser's private window or double-checking it in another browser?

Hope this helps!

**Comment by greenweb** [comment]
Thanks, @tomasstark close but no cigar ;-) - that was the first thing I did before posting here, I also dumped the server cache. Unfortunately, this problem crops up in multiple browsers. The client's site is https://www.infoplusaccounting.com/ I checked and they are running an updated Make Theme (v1.9.12) and Make Pro plug-in ( v1.9.14 )

**Comment by tomasstark** [comment]
Got it, @greenweb. The issue is that [Font Awesome CSS on that website](https://www.infoplusaccounting.com/wp-content/themes/make/css/libs/font-awesome/css/font-awesome.min.css?ver=4.6.1) still loads up version 4.7.0. This is an issue on our end since we didn't bump the version to 5.0.13. We're going to patch this up. Meanwhile, to get this working, manually flushing that file on your server will help.

Thanks!
