### ISSUE TITLE
Can't remove widget area from widget admin after converting widget area back to post area

### ISSUE THREAD

**Issue by tonyzeoli** [thethemefoundry/make#368]
When I set a widget area in a column and then revert from a widgetized area back to a column post area, the widget area will not remove itself from the widget admin. I've made sure to remove the widget from the widget area, update the page, dump my cache, and then look at the widget admin again to see if the widget area disappears, but it does not. Seems to be stuck there.

**Comment by tomasstark** [comment]
Hey @tonyzeoli,

Thanks for reporting this. It's on our radar currently to improve this. As it turns out, the only way to get rid of those widget areas for now is manually deleting them from *wp_options* database table, where *option_name* is *ttfmp-builder-sidebars*.

Hope this helps!
