### ISSUE TITLE
After clear cache, Make Builder template view disappears, but short codes remain in place

### ISSUE THREAD

**Issue by tonyzeoli** [thethemefoundry/make#372]
There seems to be an issue where when working on a page, after clearing the cache, the Make Builder template panels disappear when the template is set to Builder, but the shortcodes are still available in the Default view.

**Comment by tomasstark** [comment]
Hey @tonyzeoli 👋

Would you mind sharing more details on this? What caching plugin do you use? Are there any other plugins that might play some role here? Have you tried deactivating them all and see if you can still replicate?

Let me know! 🙂
