### ISSUE TITLE
Accessibility

### ISSUE THREAD

**Issue by tollmanz** [thethemefoundry/make#66]
I think we should strive to make this theme accessible. The Theme Review Team has some great [draft guidelines](http://make.wordpress.org/themes/guidelines/guidelines-accessibility/) that we can work through. I can take the lead on this and ping others as needed.
### Accessibility improvements
- [ ] Change post titles and other non-site title h1's into h2's
- [ ] Remove `a` tag title attributes
- [ ] Custom logo: add site title text for screen readers
- [x] Social icons: remove title attribute from markup
- [x] Social icons: add textual name to each social icon (for screen readers), then hide w/ CSS
- [ ] Turn off Banner section's "autoplay" by default
- [ ] Add post title to "read more" links for screen readers
- [ ] Add visual focus highlight to links
- [ ] Don't use `display: none` on navigation dropdowns
- [ ] Make sure navigation skip link meets [the guideline](http://make.wordpress.org/themes/guidelines/guidelines-accessibility/)

**Comment by coreymckrill** [comment]
From a [ticket in the Help Center](https://thethemefoundry.com/questions/topic/minor-verbiage-and-accessibility-bugs-in-make/):

> It’s great that you have a Skip to Content link. Now you should make it visible on :focus, since not all people who navigate with a keyboard are visually impaired. (More broadly, you should never be able to hit TAB and not see where focus went.) It should also probably come before the Site Title. You can see this behavior in the demos of any default WP theme (like [Twenty Sixteen](https://twentysixteendemo.wordpress.com/?demo)). Just hit tab and the link becomes visible. This is [the requirement for accessibility-ready themes in the WordPress repo](https://make.wordpress.org/themes/handbook/review/accessibility/required/#skip-links), so I’d recommend that you do this and aim to make Make an accessibility-ready theme!

**Comment by coreymckrill** [comment]
https://make.wordpress.org/core/handbook/best-practices/coding-standards/accessibility-coding-standards/
